insert into public.tours (
  slug,
  title,
  title_en,
  pueblo_slug,
  description,
  description_en,
  full_description,
  full_description_en,
  price_min,
  price_max,
  price,
  currency,
  duration_hours,
  duration_text,
  difficulty,
  min_guests,
  max_guests,
  meeting_point,
  cover_image,
  images,
  highlights,
  included,
  not_included,
  what_to_bring,
  itinerary,
  available_days,
  start_times,
  is_active,
  is_featured,
  rating,
  category
) values (
  'cabalgata-panoramica-san-pedro',
  'Free Riders Horseback Volcano View Trail Adventure',
  'Free Riders Horseback Volcano View Trail Adventure',
  'san-pedro',
  'Cabalgata panoramica con vistas al lago y volcanes desde San Pedro, operada junto a Free Riders Guild y Rancho Moises, ideal para principiantes y niveles mas avanzados.',
  'Horseback trail adventure with lake and volcano views from San Pedro, operated together with Free Riders Guild and Rancho Moises, suitable for beginners as well as more advanced riders.',
  'Free Riders Horseback Volcano View Trail Adventure es una experiencia de cabalgata en San Pedro pensada para viajeros que quieren algo distinto al hiking clasico. Segun la informacion actual de la proveedora, el ride se realiza los martes y jueves, con vistas abiertas del lago, volcanes y montanas, e incluye instruccion basica antes de salir. El punto de encuentro puede confirmarse entre San Pedro Dock / Crown Coffee o directamente en Rancho Moises, segun el horario elegido al reservar.',
  'Free Riders Horseback Volcano View Trail Adventure is a horseback experience in San Pedro for travelers looking for something different from the classic hike. Based on the provider information we have so far, the ride runs on Tuesdays and Thursdays, features open views of the lake, volcanoes, and mountains, and includes basic instruction before departure. The meetup is confirmed on booking and may be either San Pedro Dock / Crown Coffee or directly at Rancho Moises depending on the selected schedule.',
  350,
  700,
  350,
  'GTQ',
  3,
  '3 horas',
  'Todos los niveles',
  1,
  6,
  'Meetup por confirmar entre San Pedro Dock / Crown Coffee o Rancho Moises',
  '/images/tours/san-pedro/cabalgata-panoramica-san-pedro.png',
  array[
    '/images/tours/san-pedro/cabalgata-panoramica-san-pedro.png'
  ],
  array[
    'Vistas del lago, volcanes y montanas alrededor de San Pedro',
    'Bienvenida para principiantes con instruccion basica antes del ride',
    'Opciones para riders intermedios o avanzados segun disponibilidad'
  ],
  array[
    'Caballo para el recorrido',
    'Instruccion basica antes de salir',
    'Cabalgata panoramica con Free Riders Guild y Rancho Moises'
  ],
  array[
    'Transporte hasta el punto de salida',
    'Fotos profesionales',
    'Comidas o bebidas',
    'Propinas'
  ],
  array[
    'Pantalon comodo o leggings',
    'Zapatos cerrados',
    'Agua',
    'Protector solar',
    'Camara o telefono con bateria'
  ],
  '[
    {"time":"9:30 AM","title":"Meetup en San Pedro","description":"Encuentro en San Pedro Dock / Crown Coffee o confirmacion para llegar a Rancho Moises."},
    {"time":"10:00 AM","title":"Instruccion y salida","description":"Introduccion basica para principiantes y preparacion antes de comenzar la cabalgata."},
    {"time":"11:00 AM","title":"Ruta panoramica","description":"Recorrido por caminos rurales con vistas al lago, montanas y volcanes."},
    {"time":"1:00 PM","title":"Cierre del ride","description":"Fin de la experiencia y regreso al punto acordado."}
  ]'::jsonb,
  array['martes','jueves'],
  array['10:00'],
  true,
  true,
  5.0,
  'Horseback'
)
on conflict (slug) do update
set
  title = excluded.title,
  title_en = excluded.title_en,
  pueblo_slug = excluded.pueblo_slug,
  description = excluded.description,
  description_en = excluded.description_en,
  full_description = excluded.full_description,
  full_description_en = excluded.full_description_en,
  price_min = excluded.price_min,
  price_max = excluded.price_max,
  price = excluded.price,
  currency = excluded.currency,
  duration_hours = excluded.duration_hours,
  duration_text = excluded.duration_text,
  difficulty = excluded.difficulty,
  min_guests = excluded.min_guests,
  max_guests = excluded.max_guests,
  meeting_point = excluded.meeting_point,
  cover_image = excluded.cover_image,
  images = excluded.images,
  highlights = excluded.highlights,
  included = excluded.included,
  not_included = excluded.not_included,
  what_to_bring = excluded.what_to_bring,
  itinerary = excluded.itinerary,
  available_days = excluded.available_days,
  start_times = excluded.start_times,
  is_active = excluded.is_active,
  is_featured = excluded.is_featured,
  rating = excluded.rating,
  category = excluded.category;
